// This file is auto-generated by @hey-api/openapi-ts

export type AppControllerGetHelloResponse = unknown;

export type $OpenApiTs = {
    '/': {
        get: {
            res: {
                200: unknown;
            };
        };
    };
};